<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="1" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-06-17T13:03:34 IST" name="Default suite" finished-at="2022-06-17T13:04:19 IST" duration-ms="45466">
    <groups>
      <group name="Sanity">
        <method signature="TestCases.loginToPageTest()[pri:0, instance:SSofFailedTest@6a192cfe]" name="loginToPageTest" class="TestCases"/>
        <method signature="TestCases.verifyzerodhaLogo()[pri:0, instance:SSofFailedTest@6a192cfe]" name="verifyzerodhaLogo" class="TestCases"/>
      </group> <!-- Sanity -->
      <group name="Regression">
        <method signature="TestCases.verifyTitleTest()[pri:0, instance:SSofFailedTest@6a192cfe]" name="verifyTitleTest" class="TestCases"/>
        <method signature="TestCases.verifykitLogoTest()[pri:0, instance:SSofFailedTest@6a192cfe]" name="verifykitLogoTest" class="TestCases"/>
      </group> <!-- Regression -->
    </groups>
    <test started-at="2022-06-17T13:03:34 IST" name="Default test" finished-at="2022-06-17T13:04:19 IST" duration-ms="45466">
      <class name="SSofFailedTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:SSofFailedTest@6a192cfe]" started-at="2022-06-17T13:03:34 IST" name="setup" finished-at="2022-06-17T13:03:43 IST" duration-ms="9296" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyKiteLogoTest1()[pri:0, instance:SSofFailedTest@6a192cfe]" started-at="2022-06-17T13:03:43 IST" name="verifyKiteLogoTest1" finished-at="2022-06-17T13:03:43 IST" duration-ms="202" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyKiteLogoTest1 -->
        <test-method is-config="true" signature="exit(org.testng.ITestResult)[pri:0, instance:SSofFailedTest@6a192cfe]" started-at="2022-06-17T13:03:43 IST" name="exit" finished-at="2022-06-17T13:03:48 IST" duration-ms="4865" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyKiteLogoTest1 status=SUCCESS method=SSofFailedTest.verifyKiteLogoTest1()[pri:0, instance:SSofFailedTest@6a192cfe] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exit -->
        <test-method is-config="true" signature="exit()[pri:0, instance:SSofFailedTest@6a192cfe]" started-at="2022-06-17T13:03:48 IST" name="exit" finished-at="2022-06-17T13:03:48 IST" duration-ms="168" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exit -->
        <test-method is-config="true" signature="setup()[pri:0, instance:SSofFailedTest@6a192cfe]" started-at="2022-06-17T13:03:48 IST" name="setup" finished-at="2022-06-17T13:03:55 IST" duration-ms="6982" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="loginToPageTest()[pri:0, instance:SSofFailedTest@6a192cfe]" started-at="2022-06-17T13:03:55 IST" name="loginToPageTest" finished-at="2022-06-17T13:03:55 IST" duration-ms="5" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "Pages.LoginPage.loginToPage()" because "this.login" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "Pages.LoginPage.loginToPage()" because "this.login" is null
at TestCases.loginToPageTest(TestCases.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToPageTest -->
        <test-method is-config="true" signature="exit(org.testng.ITestResult)[pri:0, instance:SSofFailedTest@6a192cfe]" started-at="2022-06-17T13:03:55 IST" name="exit" finished-at="2022-06-17T13:03:56 IST" duration-ms="983" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginToPageTest status=FAILURE method=TestCases.loginToPageTest()[pri:0, instance:SSofFailedTest@6a192cfe] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exit -->
        <test-method is-config="true" signature="exit()[pri:0, instance:SSofFailedTest@6a192cfe]" started-at="2022-06-17T13:03:56 IST" name="exit" finished-at="2022-06-17T13:03:57 IST" duration-ms="266" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exit -->
        <test-method is-config="true" signature="setup()[pri:0, instance:SSofFailedTest@6a192cfe]" started-at="2022-06-17T13:03:57 IST" name="setup" finished-at="2022-06-17T13:04:02 IST" duration-ms="5512" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyTitleTest()[pri:0, instance:SSofFailedTest@6a192cfe]" started-at="2022-06-17T13:04:02 IST" name="verifyTitleTest" finished-at="2022-06-17T13:04:02 IST" duration-ms="4" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "Pages.LoginPage.verifyTitle()" because "this.login" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "Pages.LoginPage.verifyTitle()" because "this.login" is null
at TestCases.verifyTitleTest(TestCases.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTitleTest -->
        <test-method is-config="true" signature="exit(org.testng.ITestResult)[pri:0, instance:SSofFailedTest@6a192cfe]" started-at="2022-06-17T13:04:02 IST" name="exit" finished-at="2022-06-17T13:04:03 IST" duration-ms="1052" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyTitleTest status=FAILURE method=TestCases.verifyTitleTest()[pri:0, instance:SSofFailedTest@6a192cfe] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exit -->
        <test-method is-config="true" signature="exit()[pri:0, instance:SSofFailedTest@6a192cfe]" started-at="2022-06-17T13:04:03 IST" name="exit" finished-at="2022-06-17T13:04:04 IST" duration-ms="215" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exit -->
        <test-method is-config="true" signature="setup()[pri:0, instance:SSofFailedTest@6a192cfe]" started-at="2022-06-17T13:04:04 IST" name="setup" finished-at="2022-06-17T13:04:09 IST" duration-ms="5389" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifykitLogoTest()[pri:0, instance:SSofFailedTest@6a192cfe]" started-at="2022-06-17T13:04:09 IST" name="verifykitLogoTest" finished-at="2022-06-17T13:04:09 IST" duration-ms="14" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "Pages.LoginPage.verifykitLogo()" because "this.login" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "Pages.LoginPage.verifykitLogo()" because "this.login" is null
at TestCases.verifykitLogoTest(TestCases.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifykitLogoTest -->
        <test-method is-config="true" signature="exit(org.testng.ITestResult)[pri:0, instance:SSofFailedTest@6a192cfe]" started-at="2022-06-17T13:04:09 IST" name="exit" finished-at="2022-06-17T13:04:10 IST" duration-ms="1004" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifykitLogoTest status=FAILURE method=TestCases.verifykitLogoTest()[pri:0, instance:SSofFailedTest@6a192cfe] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exit -->
        <test-method is-config="true" signature="exit()[pri:0, instance:SSofFailedTest@6a192cfe]" started-at="2022-06-17T13:04:10 IST" name="exit" finished-at="2022-06-17T13:04:10 IST" duration-ms="245" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exit -->
        <test-method is-config="true" signature="setup()[pri:0, instance:SSofFailedTest@6a192cfe]" started-at="2022-06-17T13:04:10 IST" name="setup" finished-at="2022-06-17T13:04:18 IST" duration-ms="7658" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyzerodhaLogo()[pri:0, instance:SSofFailedTest@6a192cfe]" started-at="2022-06-17T13:04:18 IST" name="verifyzerodhaLogo" finished-at="2022-06-17T13:04:18 IST" duration-ms="7" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "Pages.LoginPage.verifyzerodhaLogo()" because "this.login" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "Pages.LoginPage.verifyzerodhaLogo()" because "this.login" is null
at TestCases.verifyzerodhaLogo(TestCases.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyzerodhaLogo -->
        <test-method is-config="true" signature="exit(org.testng.ITestResult)[pri:0, instance:SSofFailedTest@6a192cfe]" started-at="2022-06-17T13:04:18 IST" name="exit" finished-at="2022-06-17T13:04:19 IST" duration-ms="1121" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyzerodhaLogo status=FAILURE method=TestCases.verifyzerodhaLogo()[pri:0, instance:SSofFailedTest@6a192cfe] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exit -->
        <test-method is-config="true" signature="exit()[pri:0, instance:SSofFailedTest@6a192cfe]" started-at="2022-06-17T13:04:19 IST" name="exit" finished-at="2022-06-17T13:04:19 IST" duration-ms="254" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exit -->
      </class> <!-- SSofFailedTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
